name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
    - uses: actions/checkout@v6
    - run: swift build --build-tests
    - run: swift test --skip-build --enable-swift-testing --parallel
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        IMAGES_API_TOKEN: ${{ secrets.IMAGES_API_TOKEN }}
        EMAIL_SERVICE_API_TOKEN: ${{ secrets.EMAIL_SERVICE_API_TOKEN }}
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
      - uses: actions/checkout@v6
      - run: swift format lint -r -p -s .
